# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaserTest < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainlink/releasertest/releases/download/v0.1.0/ReleaserTest_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "53840dafd43975af53360a198872ad2e570e99aa77c6978310e265ceb6941713"
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainlink/releasertest/releases/download/v0.1.0/ReleaserTest_0.1.0_Darwin_arm64.tar.gz"
      sha256 "4a35ae601541ceb855e386e11b7e413c2d0b356cf5d88b3f09cac9d62eed2ce1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chainlink/releasertest/releases/download/v0.1.0/ReleaserTest_0.1.0_Linux_x86_64.tar.gz"
      sha256 "e31b597e06fb10f0023dfeefcb33e8b5a703065189ef725769ca5a7ca4c67ab8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chainlink/releasertest/releases/download/v0.1.0/ReleaserTest_0.1.0_Linux_arm64.tar.gz"
      sha256 "116f2a648ebc85b01eebac9eb62252b9a478bacc3f59cb80c5ba12fc370b6e8f"
    end
  end

  def install
    bin.install "ReleaserTest"
  end
end
