# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaserTest < Formula
  desc ""
  homepage ""
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainlink/releasertest/releases/download/v0.2.0/ReleaserTest_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "868b6168c714e1e948e33a15b251f90de4a9d73cf4f0955e63dea48fe47a4eb3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainlink/releasertest/releases/download/v0.2.0/ReleaserTest_0.2.0_Darwin_arm64.tar.gz"
      sha256 "81d9e4bfd80506789f50cbe5412e8ae93de99a097be208b2d9e8ef1de9cc75cd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chainlink/releasertest/releases/download/v0.2.0/ReleaserTest_0.2.0_Linux_x86_64.tar.gz"
      sha256 "7ed4fe339db51618afdcd932ffd685072773216dca52c303f5aa24f1e0fd67ed"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chainlink/releasertest/releases/download/v0.2.0/ReleaserTest_0.2.0_Linux_arm64.tar.gz"
      sha256 "b923ca84b12485005380ad2567375a35bdd799e4848b6ef24c065c141a638c40"
    end
  end

  def install
    bin.install "ReleaserTest"
  end
end
